name: Build and Publish MkDocs Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install MkDocs Material
        run: |
          pip install mkdocs-material

      - name: Build MkDocs site from 'markdown' folder
        run: |
          mkdocs build -f mkdocs.yml -d site
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
